
-- TRABALHO DE BANCO DE DADOS II — STREAMPLAY

-- 1. CRIAÇÃO DAS TABELAS

DROP TABLE IF EXISTS ESTATISTICA_VIDEO CASCADE;
DROP TABLE IF EXISTS AVALIACAO CASCADE;
DROP TABLE IF EXISTS VISUALIZACAO CASCADE;
DROP TABLE IF EXISTS EPISODIO CASCADE;
DROP TABLE IF EXISTS TEMPORADA CASCADE;
DROP TABLE IF EXISTS VIDEO_CATEGORIA CASCADE;
DROP TABLE IF EXISTS CATEGORIA CASCADE;
DROP TABLE IF EXISTS VIDEO CASCADE;
DROP TABLE IF EXISTS ASSINATURA CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS PLANO CASCADE;

-- TABELA DE PLANOS
CREATE TABLE PLANO (
ID_PLANO SERIAL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL UNIQUE,
VALOR NUMERIC(10,2) NOT NULL CHECK (VALOR >= 0),
QUALIDADE VARCHAR(20) NOT NULL,
LIMITE_TELAS INTEGER NOT NULL CHECK (LIMITE_TELAS > 0)
);

-- TABELA DE USUÁRIOS
CREATE TABLE USUARIO (
ID_USUARIO SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(150) NOT NULL UNIQUE,
SENHA VARCHAR(100) NOT NULL,
DATA_CADASTRO DATE NOT NULL DEFAULT CURRENT_DATE,
ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

-- ASSINATURAS
CREATE TABLE ASSINATURA (
ID_ASSINATURA SERIAL PRIMARY KEY,
ID_USUARIO INTEGER NOT NULL,
ID_PLANO INTEGER NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE,
STATUS VARCHAR(20) NOT NULL DEFAULT 'ATIVA',

CONSTRAINT FK_ASSINATURA_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

CONSTRAINT FK_ASSINATURA_PLANO
    FOREIGN KEY (ID_PLANO)
    REFERENCES PLANO(ID_PLANO),

CONSTRAINT CK_ASSINATURA_DATAS
    CHECK (DATA_FIM IS NULL OR DATA_FIM >= DATA_INICIO)


);

-- VÍDEOS
CREATE TABLE VIDEO (
ID_VIDEO SERIAL PRIMARY KEY,
TITULO VARCHAR(200) NOT NULL,
SINOPSE TEXT,
ANO_LANCAMENTO INTEGER,
DURACAO_MINUTOS INTEGER NOT NULL CHECK (DURACAO_MINUTOS > 0),
TIPO VARCHAR(30) NOT NULL,
CLASSIFICACAO VARCHAR(10),
DISPONIVEL BOOLEAN NOT NULL DEFAULT TRUE,

CONSTRAINT CK_VIDEO_TIPO
    CHECK (
        TIPO IN (
            'FILME',
            'SERIE',
            'DOCUMENTARIO',
            'ANIMACAO',
            'SHOW'
        )
    )
);

-- CATEGORIAS
CREATE TABLE CATEGORIA (
ID_CATEGORIA SERIAL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL UNIQUE
);

-- RELACIONAMENTO N:N ENTRE VIDEO E CATEGORIA
CREATE TABLE VIDEO_CATEGORIA (
ID_VIDEO INTEGER NOT NULL,
ID_CATEGORIA INTEGER NOT NULL,

PRIMARY KEY (ID_VIDEO, ID_CATEGORIA),

CONSTRAINT FK_VC_VIDEO
    FOREIGN KEY (ID_VIDEO)
    REFERENCES VIDEO(ID_VIDEO)
    ON DELETE CASCADE,

CONSTRAINT FK_VC_CATEGORIA
    FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIA(ID_CATEGORIA)
    ON DELETE CASCADE
);

-- TEMPORADAS
CREATE TABLE TEMPORADA (
ID_TEMPORADA SERIAL PRIMARY KEY,
ID_VIDEO INTEGER NOT NULL,
NUMERO INTEGER NOT NULL CHECK (NUMERO > 0),
ANO_LANCAMENTO INTEGER,

CONSTRAINT FK_TEMPORADA_VIDEO
    FOREIGN KEY (ID_VIDEO)
    REFERENCES VIDEO(ID_VIDEO)
    ON DELETE CASCADE,

CONSTRAINT UK_TEMPORADA
    UNIQUE (ID_VIDEO, NUMERO)
);

-- EPISÓDIOS
CREATE TABLE EPISODIO (
ID_EPISODIO SERIAL PRIMARY KEY,
ID_TEMPORADA INTEGER NOT NULL,
NUMERO INTEGER NOT NULL CHECK (NUMERO > 0),
TITULO VARCHAR(200) NOT NULL,
DURACAO_MINUTOS INTEGER NOT NULL CHECK (DURACAO_MINUTOS > 0),

CONSTRAINT FK_EPISODIO_TEMPORADA
    FOREIGN KEY (ID_TEMPORADA)
    REFERENCES TEMPORADA(ID_TEMPORADA)
    ON DELETE CASCADE,

CONSTRAINT UK_EPISODIO
    UNIQUE (ID_TEMPORADA, NUMERO)


);

-- REGISTRO DE VISUALIZAÇÕES
CREATE TABLE VISUALIZACAO (
ID_VISUALIZACAO SERIAL PRIMARY KEY,
ID_USUARIO INTEGER NOT NULL,
ID_VIDEO INTEGER NOT NULL,
DATA_HORA_INICIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATA_HORA_FIM TIMESTAMP,
SEGUNDOS_ASSISTIDOS INTEGER NOT NULL DEFAULT 0
CHECK (SEGUNDOS_ASSISTIDOS >= 0),

CONSTRAINT FK_VISUALIZACAO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO),

CONSTRAINT FK_VISUALIZACAO_VIDEO
    FOREIGN KEY (ID_VIDEO)
    REFERENCES VIDEO(ID_VIDEO)
);

-- AVALIAÇÕES
CREATE TABLE AVALIACAO (
ID_USUARIO INTEGER NOT NULL,
ID_VIDEO INTEGER NOT NULL,
NOTA INTEGER NOT NULL CHECK (NOTA BETWEEN 1 AND 5),
DATA_AVALIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (ID_USUARIO, ID_VIDEO),

CONSTRAINT FK_AVALIACAO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
    ON DELETE CASCADE,

CONSTRAINT FK_AVALIACAO_VIDEO
    FOREIGN KEY (ID_VIDEO)
    REFERENCES VIDEO(ID_VIDEO)
    ON DELETE CASCADE
);

-- TABELA AUXILIAR DE ESTATÍSTICAS (PARA TRIGGER 2)
CREATE TABLE ESTATISTICA_VIDEO (
ID_VIDEO INTEGER PRIMARY KEY,
QUANTIDADE_AVALIACOES INTEGER DEFAULT 0,
SOMA_NOTAS INTEGER DEFAULT 0,
NOTA_MEDIA NUMERIC(5,2) DEFAULT 0,

CONSTRAINT FK_ESTATISTICA_VIDEO
    FOREIGN KEY (ID_VIDEO)
    REFERENCES VIDEO(ID_VIDEO)
    ON DELETE CASCADE
);